// Generated by CoffeeScript 1.8.0
var mod, _i, _len, _ref;

_ref = 'utils CoreObject Dictionary DictionaryEx RecordStore MergedRecordStore Model Database'.split(' ');
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  mod = _ref[_i];
  module.exports[mod] = require('./' + mod);
}
