// Generated by CoffeeScript 1.8.0
var _;

_ = require('lodash');

_.mixin(require('underscore.inflections'));

_.mixin({
  copy: function(object) {
    return _.cloneDeep(object);
  },
  log: function() {
    return console.log.apply(console, arguments);
  },
  "throw": function(Class, message) {
    if (arguments.length < 2) {
      message = Class;
      Class = Error;
    }
    throw new Class(message);
  },
  lock: function(object, propertyName, enumerable) {
    var val;
    if (enumerable == null) {
      enumerable = true;
    }
    val = object[propertyName];
    Object.defineProperty(object, propertyName, {
      get: (function() {
        return val;
      }),
      set: (function() {
        return utils["throw"]("property " + propertyName + " is read-only");
      }),
      configurable: false,
      enumerable: enumerable
    });
    return object;
  }
});

module.exports = _;
